services:
  - type: web_service
    name: identification-backend
    env: python
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT

  - type: static_site
    name: identification-frontend
    env: static
    root: frontend
    buildCommand: yarn install && npx expo export:web web-build
    publishPath: web-build
